### ISSUE TITLE
Error: Missing "./AgGridSvelte.svelte" specifier in "ag-grid-svelte" package

### ISSUE THREAD

**Issue by brandonp-ais** [MichaelKim/ag-grid-svelte#10]
**Versions**

"@sveltejs/kit": "^1.16.0",
"ag-grid-community": "^29.3.4",
"ag-grid-svelte": "^0.2.0",

Get error when running build:

<details>
<summary>
Stack trace
</summary>
<pre>
[commonjs--resolver] Missing "./AgGridSvelte.svelte" specifier in "ag-grid-svelte" package
error during build:
Error: Missing "./AgGridSvelte.svelte" specifier in "ag-grid-svelte" package
    at e (file:///D:/projects/accessit-v10-mgmt/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:16649:25)
    at n (file:///D:/projects/accessit-v10-mgmt/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:16649:627)
    at o (file:///D:/projects/accessit-v10-mgmt/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:16649:1297)
    at resolveExportsOrImports (file:///D:/projects/accessit-v10-mgmt/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:23407:20)
    at resolveDeepImport (file:///D:/projects/accessit-v10-mgmt/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:23426:31)
    at tryNodeResolve (file:///D:/projects/accessit-v10-mgmt/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:23115:20)
    at Object.resolveId (file:///D:/projects/accessit-v10-mgmt/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:22876:28)
    at Object.handler (file:///D:/projects/accessit-v10-mgmt/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:46631:19)
    at file:///D:/projects/accessit-v10-mgmt/node_modules/rollup/dist/es/shared/node-entry.js:24526:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/projects/accessit-v10-mgmt/node_modules/rollup/dist/es/shared/node-entry.js:24426:28)
 ELIFECYCLE  Command failed with exit code 1.
</pre>
</details>

Have tried changing import in the following ways:

```svelte
import AgGridSvelte from 'ag-grid-svelte';
import AgGridSvelte from 'ag-grid-svelte/AgGridSvelte.svelte';
import AgGridSvelte from 'ag-grid-svelte/dist/AgGridSvelte.svelte';
```

NB: Still working when running with dev server.

**Comment by brandonp-ais** [comment]
BTW, thank you for this package, it is really great!

I'll have a look at making a simple repro + having a look myself. Made this issue so at least it is noted down.

**Comment by MichaelKim** [comment]
I suggest going with the first way of importing as the component is available as the default export.

Are you using a specific Vite config in addition to SvelteKit?

**Comment by brandonp-ais** [comment]
Sorry, false alarm, there was an bad import in a forgotten "example" component. Thanks for your time.
